apiVersion: v1
kind: Pod
metadata:
  name: cockpit
  namespace: default 
spec:
  containers:
  - name: cockpit
    image: kaizheh/ubuntu-cockpit
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /host
        name: host
      - mountPath: /dev
        name: dev
      - mountPath: /run
        name: run
  hostPID: false
  hostIPC: false
  hostNetwork: true
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory
  - name: dev
    hostPath:
      path: /dev
      type: Directory
  - name: run
    hostPath:
      path: /run
      type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: packet-beat
  namespace: default 
spec:
  containers:
  - name: packet-beat
    image: docker.elastic.co/beats/packetbeat:6.5.4
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
  hostPID: false
  hostIPC: false
  hostNetwork: true
